export const mockedFilms = [
  {
    _id: '1',
    title: 'Wściekłość',
    originalTitle: 'Kein Tier. So Wild.',
    year: 2025,
    genres: [12, 55],
    description: 'Młoda kobieta z wpływowej rodziny staje do walki o władzę w wojnie gangów na przedmieściach Berlina.',
    imdb: 30195482,
  },
  {
    _id: '2',
    title: 'Sekrety i kłamstwa',
    originalTitle: 'Secrets & Lies',
    year: 1996,
    genres: [29, 12],
    description: 'Czarnoskóra okulistka postanawia odnaleźć biologiczną matkę, która jest na skraju załamania.',
    imdb: 117589,
  },
  {
    _id: '3',
    title: 'Materialiści',
    originalTitle: 'Materialists',
    year: 2025,
    genres: [30],
    description:
      'Dochodowy interes swatki komplikuje się, gdy nawiązuje ona trójkąt miłosny, który zagraża jej klientom.',
    imdb: 30253473,
  },
  {
    _id: '1',
    title: 'Wściekłość',
    originalTitle: 'Kein Tier. So Wild.',
    year: 2025,
    genres: [12, 55],
    description: 'Młoda kobieta z wpływowej rodziny staje do walki o władzę w wojnie gangów na przedmieściach Berlina.',
    imdb: 30195482,
  },
  {
    _id: '2',
    title: 'Sekrety i kłamstwa',
    originalTitle: 'Secrets & Lies',
    year: 1996,
    genres: [29, 12],
    description: 'Czarnoskóra okulistka postanawia odnaleźć biologiczną matkę, która jest na skraju załamania.',
    imdb: 117589,
  },
  {
    _id: '3',
    title: 'Materialiści',
    originalTitle: 'Materialists',
    year: 2025,
    genres: [30],
    description:
      'Dochodowy interes swatki komplikuje się, gdy nawiązuje ona trójkąt miłosny, który zagraża jej klientom.',
    imdb: 30253473,
  },
  {
    _id: '1',
    title: 'Wściekłość',
    originalTitle: 'Kein Tier. So Wild.',
    year: 2025,
    genres: [12, 55],
    description: 'Młoda kobieta z wpływowej rodziny staje do walki o władzę w wojnie gangów na przedmieściach Berlina.',
    imdb: 30195482,
  },
  {
    _id: '2',
    title: 'Sekrety i kłamstwa',
    originalTitle: 'Secrets & Lies',
    year: 1996,
    genres: [29, 12],
    description: 'Czarnoskóra okulistka postanawia odnaleźć biologiczną matkę, która jest na skraju załamania.',
    imdb: 117589,
  },
  {
    _id: '3',
    title: 'Materialiści',
    originalTitle: 'Materialists',
    year: 2025,
    genres: [30],
    description:
      'Dochodowy interes swatki komplikuje się, gdy nawiązuje ona trójkąt miłosny, który zagraża jej klientom.',
    imdb: 30253473,
  },
];
